helm:
  name: netcdf-subset-test
  group: rda-test
  path: / 
  autoscale:
    minReplicaCount: 1 #Minimum number of replicas to run for the deployment
    maxReplicaCount: 3 #Maximum number of replicas to run for the deployment
    cpuAverageUtilization: 3 # Average CPU load to maintain across all replicas
  tls:
    fqdn: subset-test.k8s.ucar.edu #FQDN
    #The TLS secretName should be unique to the FQDN as it is used to deploy a TLS certificate for that specific FQDN
    #In the example below replace #HOST with the application name for a unique incommon issued certificate
    secretName: incommon-cert-netcdf-subset-test
  container: 
    image: hub.k8s.ucar.edu/docker/cislcloudpilot/docs:2024-02-15.22 #The container image name to use and container registry to use (Docker Hub is the default)
    port: 8888 #The container port to expose
    memory: 4 # The amount of memory (G) to allocate for the image
    cpu: 1 # The number of CPUs to allocate for the image
  volume1:
    name: rda-collections
    server: gladedm1.ucar.edu
    path: /gpfs/csfs1/collections/rda
    readOnly: true
  
